# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openspdd < Formula
  desc "AI Coding Assistant Command Template Manager"
  homepage "https://github.com/gszhangwei/open-spdd"
  version "0.4.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gszhangwei/open-spdd/releases/download/v0.4.6/openspdd_0.4.6_darwin_amd64.tar.gz"
      sha256 "a6f6b7ef8e13247a3aabdee8e99fe6243ebe6c5c7c0381190a652d87fd14fd53"

      define_method(:install) do
        bin.install "openspdd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gszhangwei/open-spdd/releases/download/v0.4.6/openspdd_0.4.6_darwin_arm64.tar.gz"
      sha256 "db5c8b027134bf2b83b5746743814414bd60168f1714aef0f9a2d18226a80328"

      define_method(:install) do
        bin.install "openspdd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gszhangwei/open-spdd/releases/download/v0.4.6/openspdd_0.4.6_linux_amd64.tar.gz"
      sha256 "d78d519c18cc45c34ee0fb6239746077a6753b36826e4f877850391745fb8ab1"
      define_method(:install) do
        bin.install "openspdd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gszhangwei/open-spdd/releases/download/v0.4.6/openspdd_0.4.6_linux_arm64.tar.gz"
      sha256 "c8ee3f5f5f53ae6dc24ed88d3d456acd4edbed4ecdf924368a32ffbdef7332bb"
      define_method(:install) do
        bin.install "openspdd"
      end
    end
  end

  test do
    system "#{bin}/openspdd", "--version"
  end
end
