# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openspdd < Formula
  desc "AI Coding Assistant Command Template Manager"
  homepage "https://github.com/gszhangwei/open-spdd"
  version "0.4.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gszhangwei/open-spdd/releases/download/v0.4.10/openspdd_0.4.10_darwin_amd64.tar.gz"
      sha256 "c12205d34e73b5b87eba622c4edc4fdded82e6be72c4d94c0546ef95db6b26c9"

      define_method(:install) do
        bin.install "openspdd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gszhangwei/open-spdd/releases/download/v0.4.10/openspdd_0.4.10_darwin_arm64.tar.gz"
      sha256 "e0bdd579fe3c90bab27eedd27ff5bb2725c7433b2fcf8cec17a13b1571a594af"

      define_method(:install) do
        bin.install "openspdd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gszhangwei/open-spdd/releases/download/v0.4.10/openspdd_0.4.10_linux_amd64.tar.gz"
      sha256 "d0b0805ebb3a31da7554b5d49014c8efbba2094044a1e504563795a88cae3308"
      define_method(:install) do
        bin.install "openspdd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gszhangwei/open-spdd/releases/download/v0.4.10/openspdd_0.4.10_linux_arm64.tar.gz"
      sha256 "04dbd36e7bbccf2d3d670b010bc3d49f4c3045bd0721fb0d4e9be1d4dde6ba22"
      define_method(:install) do
        bin.install "openspdd"
      end
    end
  end

  test do
    system "#{bin}/openspdd", "--version"
  end
end
